/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Mintable__factory } from "./ERC20Mintable__factory";
export { IStakingRegistry__factory } from "./IStakingRegistry__factory";
export { RollStakingFactoryV2__factory } from "./RollStakingFactoryV2__factory";
export { RollStakingRewardsV2__factory } from "./RollStakingRewardsV2__factory";
export { StakingRegistry__factory } from "./StakingRegistry__factory";
